### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by unkn0wn-us3r** [0xsha/sweetie-data#1]
Hi 0xsha,

I really appreciate your work and efforts for the infosec community. Could you please mention the license information for the project (GPL / MIT, etc). That would be really helpful.

Thanks.

**Comment by 0xsha** [comment]
Thanks fixed  in  https://github.com/0xsha/sweetie-data/commit/a2796b5dbdc509e5c3eda805208240c464be7ad1 .

**Comment by unkn0wn-us3r** [comment]
Thanks @0xsha for a quick response. Could you please add the license name (GPL / MIT, etc) as well.
Currently the License file is empty.

Thanks.

**Comment by 0xsha** [comment]
my bad https://github.com/0xsha/sweetie-data/commit/40c0caacd62b00d555a78aa13d6062ba529fd00a . thanks

**Comment by unkn0wn-us3r** [comment]
Thanks @0xsha.
